from app.model.customers import CustomerModel
from app.model.companies import CompanyModel
from app.model.admins import AdminModel
from app.model.roles import RoleModel
from app.model.deals import DealModel
from app.model.reminders import ReminderModel
from app.model.stages import StageModel
from app.model.tags import TagModel
from app.model.types import TypeModel
from app.model.customers_id import Customer_idModel
from app.model.contacts import ContactModel